version: '3.8'

services:
  # React frontend service
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network

  # Node.js Express API service
  backend:
    build: ./backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/todoapp
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mongo

  # MongoDB service
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  # Redis cache service
  redis:
    image: redis:latest
    networks:
      - app-network

  # Nginx reverse proxy service
  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
